// default package
// Generated 30 nov. 2022 10:40:10 by Hibernate Tools 5.2.12.Final

package Model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.NamedQueries;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "Alumno", catalog = "DocenciaConsultas")
@NamedQueries({
	@NamedQuery(name="Repetidores",query="select a from Alumno a where a.repetidor=true "),
	@NamedQuery(name="AlumnosEntre",query="select a from Alumno a where a.edad between :min and :max"),
	@NamedQuery(name="AlumnosDescAge",query="select a from Alumno a order by a.edad desc")
})
public class Alumno implements java.io.Serializable {
	static final long serialVersionUID=13L;

	private Long idAlumno;
	@Override
	public String toString() {
		return "Alumno [idAlumno=" + idAlumno + ", apellidos=" + apellidos + ", edad=" + edad + ", nombre=" + nombre
				+ ", repetidor=" + repetidor + "]";
	}

	private String apellidos;
	private Integer edad;
	private String nombre;
	private Boolean repetidor;
	private Set<Examen> examens = new HashSet(0);

	public Alumno() {
	}

	public Alumno(String apellidos, Integer edad, String nombre, Boolean repetidor, Set<Examen> examens) {
		this.apellidos = apellidos;
		this.edad = edad;
		this.nombre = nombre;
		this.repetidor = repetidor;
		this.examens = examens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAlumno", unique = true, nullable = false)
	public Long getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Long idAlumno) {
		this.idAlumno = idAlumno;
	}

	@Column(name = "apellidos")
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "repetidor")
	public Boolean getRepetidor() {
		return this.repetidor;
	}

	public void setRepetidor(Boolean repetidor) {
		this.repetidor = repetidor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alumno")
	public Set<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(Set<Examen> examens) {
		this.examens = examens;
	}

}
