// default package
// Generated 30 nov. 2022 10:40:10 by Hibernate Tools 5.2.12.Final
package Model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name = "Examen", catalog = "DocenciaConsultas")
public class Examen implements java.io.Serializable {
	
	static final long serialVersionUID=13L;

	private Long idExamen;
	private Alumno alumno;
	@Override
	public String toString() {
		return "Examen [idExamen=" + idExamen + ", alumno=" + alumno.getNombre() + ", modulo=" + modulo.getNombre() + ", fecha=" + fecha
				+ ", nota=" + nota + "]";
	}

	private Modulo modulo;
	private Date fecha;
	private Double nota;

	public Examen() {
	}

	public Examen(Alumno alumno, Modulo modulo, Date fecha, Double nota) {
		this.alumno = alumno;
		this.modulo = modulo;
		this.fecha = fecha;
		this.nota = nota;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idExamen", unique = true, nullable = false)
	public Long getIdExamen() {
		return this.idExamen;
	}

	public void setIdExamen(Long idExamen) {
		this.idExamen = idExamen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAlumno")
	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idModul")
	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "nota", precision = 22, scale = 0)
	public Double getNota() {
		return this.nota;
	}

	public void setNota(Double nota) {
		this.nota = nota;
	}

}
