// default package
// Generated 30 nov. 2022 10:40:10 by Hibernate Tools 5.2.12.Final

package Model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name = "Profesor", catalog = "DocenciaConsultas")
public class Profesor implements java.io.Serializable {
	
	static final long serialVersionUID=13L;

	private Long idProfesor;
	@Override
	public String toString() {
		return "Profesor [idProfesor=" + idProfesor + ", nombre=" + nombre + "]";
	}

	private String nombre;
	private Set<Modulo> modulos = new HashSet(0);

	public Profesor() {
	}

	public Profesor(String nombre, Set<Modulo> modulos) {
		this.nombre = nombre;
		this.modulos = modulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idProfesor", unique = true, nullable = false)
	public Long getIdProfesor() {
		return this.idProfesor;
	}

	public void setIdProfesor(Long idProfesor) {
		this.idProfesor = idProfesor;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Docencia", catalog = "DocenciaConsultas", joinColumns = {
			@JoinColumn(name = "idProfesor", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idModulo", nullable = false, updatable = false) })
	public Set<Modulo> getModulos() {
		return this.modulos;
	}

	public void setModulos(Set<Modulo> modulos) {
		this.modulos = modulos;
	}

}
