/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProvaResultSet;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

public class App {
    

    public static void main(String[] args) throws SQLException {
        
        ConnexioBD conector= new ConnexioBD();
        
        Connection con=conector.getconexio();
        
        String SQL="Select * from Persona  limit 5";
        
        Statement stm=con.createStatement();
        
        ResultSet rst=stm.executeQuery(SQL);
        
        ResultSetMetaData rstmd=rst.getMetaData();
        
        System.out.println("Hi ha un total de "+ rstmd.getColumnCount());
        
        for (int i = 1; i <= rstmd.getColumnCount(); i++) {
            System.out.printf("%-25s",rstmd.getColumnName(i) + "(" + rstmd.getColumnTypeName(i) + ")");  
        }
        System.out.println("\n===============================================================================================");
        
        while (rst.next()){
            System.out.printf("%-25d%-25s%-25s%-25d\n",
                    rst.getInt(1),
                    rst.getString("nombre"),
                    rst.getString(3),
                    rst.getInt("edad"));  
        }
        
        rst.close();
        conector.desconnect();
        
    }
}
