/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestConnection;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {
    

    public static void main(String[] args)  {
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            //String connectionUrl="jdbc:mysql://localhost:3308?user=root&password=root";
            
            //String connectionUrl="jdbc:mysql://localhost:3308";
            
            //Connection con=DriverManager.getConnection(connectionUrl);
            
//            Connection con=DriverManager.getConnection(
//                    connectionUrl,
//                    "root",
//                    "root");
            /*  Crear les porpietats i les guard
            Properties prop=new Properties();

            prop.put("user", "root");
            prop.put("password", "root");
            prop.put("userUnicode","true");
            prop.put("characterEncoding", "UTF-8");
            
            Connection con=DriverManager.getConnection(connectionUrl, prop);


            FileOutputStream fos= new FileOutputStream(new File("conf.props"));
            
            prop.store(fos, "My configuration file");

*/  

            
            /* LLegir les propietats i connectar-me*/
            
            Properties prop= new Properties();
            
            FileInputStream fis=new FileInputStream(new File("conf.props"));
            
            prop.load(fis);
            
            String connectionUrl="jdbc:mysql://"
                    +prop.getProperty("server")+":"+
                     prop.getProperty("port");
            
            Connection con=DriverManager.getConnection(connectionUrl, prop);

            
            
            
            
            
            
            
            
            
            
            
            
            System.out.println("I'm connected !!");
            
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        } catch (SQLException ex) {
            System.out.println(ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
